// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://feojlidfuvhestrmedqm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZlb2psaWRmdXZoZXN0cm1lZHFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3NzE1NDYsImV4cCI6MjA3MjM0NzU0Nn0.-V8j_0NW3FZgn3YucVt-UVQ_ZmCRmBVxWQEtQv_uhJ4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});